// Code generated by "stringer -type=Side"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SideNone-0]
	_ = x[SideExplorers-1]
	_ = x[SideHaunt-2]
	_ = x[SideNpc-3]
	_ = x[SideObject-4]
}

const _Side_name = "SideNoneSideExplorersSideHauntSideNpcSideObject"

var _Side_index = [...]uint8{0, 8, 21, 30, 37, 47}

func (i Side) String() string {
	if i < 0 || i >= Side(len(_Side_index)-1) {
		return "Side(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Side_name[_Side_index[i]:_Side_index[i+1]]
}
